hoteis/config/routes.rb
Rails.application.routes.draw do
  resources :apartamentos
  devise_for :empresas
  devise_for :clientes
  resources :hotels do
    resources :comments
  end
  resources :hotel_empresas
  resources :logins
  resources :cadastros
  mount Commontator::Engine => '/commontator'
  get 'main/index'

  root to: 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hoteis/app/models/apartamento.rb
class Apartamento < ApplicationRecord
    belongs_to :hotel, optional: true
end

hoteis/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hoteis/app/models/cliente.rb
class Cliente < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_commontator
end

hoteis/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :hotel
end

hoteis/app/models/empresa.rb
class Empresa < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

hoteis/app/models/hotel.rb
class Hotel < ApplicationRecord
    acts_as_commontable dependent: :destroy
    has_many :comments
    has_many :apartamentos
end

hoteis/app/controllers/apartamentos_controller.rb
class ApartamentosController < ApplicationController
  before_action :set_apartamento, only: [:show, :edit, :update, :destroy]

  # GET /apartamentos
  # GET /apartamentos.json
  def index
    @apartamentos = Apartamento.all
  end

  # GET /apartamentos/1
  # GET /apartamentos/1.json
  def show
  end

  # GET /apartamentos/new
  def new
    @apartamento = Apartamento.new
  end

  # GET /apartamentos/1/edit
  def edit
  end

  # POST /apartamentos
  # POST /apartamentos.json
  def create
    @apartamento = Apartamento.new(apartamento_params)

    respond_to do |format|
      if @apartamento.save
        format.html { redirect_to @apartamento, notice: 'Apartamento was successfully created.' }
        format.json { render :show, status: :created, location: @apartamento }
      else
        format.html { render :new }
        format.json { render json: @apartamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartamentos/1
  # PATCH/PUT /apartamentos/1.json
  def update
    respond_to do |format|
      if @apartamento.update(apartamento_params)
        format.html { redirect_to @apartamento, notice: 'Apartamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartamento }
      else
        format.html { render :edit }
        format.json { render json: @apartamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartamentos/1
  # DELETE /apartamentos/1.json
  def destroy
    @apartamento.destroy
    respond_to do |format|
      format.html { redirect_to apartamentos_url, notice: 'Apartamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartamento
      @apartamento = Apartamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartamento_params
      params.require(:apartamento).permit(:tamanho, :categoria, :camas, :banheiros)
    end
end

hoteis/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

hoteis/app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
end

hoteis/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @comment = @post.comments.create(params[:comment].permit(:body))
  
    end
  end
  

hoteis/app/controllers/hotel_empresa_controller.rb
class HotelEmpresaController < ApplicationController
end

hoteis/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:foto, :nome, :estrelas, :avaliacao, :local, :qtd_camas, :qnt_banheiros, :piscina, :cafe, :preço)
    end
end

hoteis/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
end

hoteis/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    
    @hotels = Hotel.all

    
  end
end

hoteis/app/controllers/startup_controller.rb
class StartupController < ApplicationController
  def index
  end
end

hoteis/app/helpers/apartamentos_helper.rb
module ApartamentosHelper
end

hoteis/app/helpers/application_helper.rb
module ApplicationHelper
end

hoteis/app/helpers/cadastros_helper.rb
module CadastrosHelper
end

hoteis/app/helpers/hotel_empresa_helper.rb
module HotelEmpresaHelper
end

hoteis/app/helpers/hotels_helper.rb
module HotelsHelper
end

hoteis/app/helpers/login_helper.rb
module LoginHelper
end

hoteis/app/helpers/main_helper.rb
module MainHelper
end

hoteis/app/helpers/startup_helper.rb
module StartupHelper
end

hoteis/app/views/apartamentos/_form.html.erb
<%= form_with(model: apartamento, local: true) do |form| %>
  <% if apartamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartamento.errors.count, "error") %> prohibited this apartamento from being saved:</h2>

      <ul>
      <% apartamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tamanho %>
    <%= form.number_field :tamanho %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.text_field :categoria %>
  </div>

  <div class="field">
    <%= form.label :camas %>
    <%= form.number_field :camas %>
  </div>

  <div class="field">
    <%= form.label :banheiros %>
    <%= form.number_field :banheiros %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hoteis/app/views/apartamentos/edit.html.erb
<h1>Editing Apartamento</h1>

<%= render 'form', apartamento: @apartamento %>

<%= link_to 'Show', @apartamento %> |
<%= link_to 'Back', apartamentos_path %>

hoteis/app/views/apartamentos/index.html.erb
<p id="notice"><%= notice %></p>

<html lang="en"><head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portfolio Item - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-portfolio-item/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-portfolio-item/css/portfolio-item.css" rel="stylesheet">

  </head>


<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="index.html">Home</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if cliente_signed_in?  %>

      <%= link_to('Logout', destroy_cliente_session_path, method: :delete) %>

      <%elsif empresa_signed_in?%>

      <%= link_to('Logout', destroy_empresa_session_path, method: :delete) %>

      <%else%>
        <%= link_to "Log in", logins_path  %>
  <% end %>



        </li>
        <li class="nav-item">
          <% if cliente_signed_in?  %>
          <%elsif empresa_signed_in?%>
          <%else%>
          <%= link_to "Cadastros", cadastros_path  %>
            <% end %>

        </li>

      </ul>
    </div>
  </div>
</nav>
<ul>

<center><h1>Apartamentos</h1><center/>

<table>
  <thead>
    <tr>
      <th>Tamanho</th>
      <th>Categoria</th>
      <th>Camas</th>
      <th>Banheiros</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartamentos.each do |apartamento| %>
      <tr>
        <td><%= apartamento.tamanho %></td>
        <td><%= apartamento.categoria %></td>
        <td><%= apartamento.camas %></td>
        <td><%= apartamento.banheiros %></td>
        <td><%= link_to 'Informações', apartamento %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><font size= "+2"><center>
<% if empresa_signed_in? %>
<%= link_to 'Novo Apartamento', new_apartamento_path %>
<% end %>
<%= link_to 'Voltar', main_index_url %>
<font/><center/>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
<%= link_to '.', new_hotel_path %>
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright © Your Website 2018</p>
  </div>
  <!-- /.container -->
</footer>
<br>

hoteis/app/views/apartamentos/new.html.erb
<center><h1>New Apartamento</h1><center/>

<center><%= render 'form', apartamento: @apartamento %><center/>

<%= link_to 'Back', apartamentos_path %>

hoteis/app/views/apartamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tamanho:</strong>
  <%= @apartamento.tamanho %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @apartamento.categoria %>
</p>

<p>
  <strong>Camas:</strong>
  <%= @apartamento.camas %>
</p>

<p>
  <strong>Banheiros:</strong>
  <%= @apartamento.banheiros %>
</p>

<%= link_to 'Editar', edit_apartamento_path(@apartamento) %> |
<%= link_to 'Voltar', apartamentos_path %>
<%= link_to 'Apagar', @apartamento, method: :delete, data: { confirm: 'Tem certeza?' } %>

hoteis/app/views/hotels/_form.html.erb
<%= form_with(model: hotel, local: true) do |form| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :estrelas %>
    <%= form.number_field :estrelas %>
  </div>

  <div class="field">
    <%= form.label :avaliacao %>
    <%= form.number_field :avaliacao %>
  </div>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local %>
  </div>

  <div class="field">
    <%= form.label :piscina %>
    <%= form.text_field :piscina %>
  </div>

  <div class="field">
    <%= form.label :cafe %>
    <%= form.text_field :cafe %>
  </div>

  <div class="field">
    <%= form.label :preço %>
    <%= form.number_field :preço %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hoteis/app/views/hotels/edit.html.erb
<h1>Editando Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

hoteis/app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<html lang="en"><head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portfolio Item - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-portfolio-item/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-portfolio-item/css/portfolio-item.css" rel="stylesheet">

  </head>


<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="index.html">Home</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if cliente_signed_in?  %>

      <%= link_to('Logout', destroy_cliente_session_path, method: :delete) %>

      <%elsif empresa_signed_in?%>

      <%= link_to('Logout', destroy_empresa_session_path, method: :delete) %>

      <%else%>
        <%= link_to "Log in", logins_path  %>
  <% end %>



        </li>
        <li class="nav-item">
          <% if cliente_signed_in?  %>
          <%elsif empresa_signed_in?%>
          <%else%>
          <%= link_to "Cadastros", cadastros_path  %>
            <% end %>

        </li>

      </ul>
    </div>
  </div>
</nav>
<ul>

<center><h1>Hotels</h1><center/>

<table>
  <thead>
    <tr>
      <th>Foto</th>
      <th>Nome</th>
      <th>Estrelas</th>
      <th>Avaliacao</th>
      <th>Local</th>
      <th>Qtd camas</th>
      <th>Qnt banheiros</th>
      <th>Piscina</th>
      <th>Cafe</th>
      <th>Preço</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><img src= "<%= hotel.foto %>" width = "700px" height="400px"</td>
        <td><%= hotel.nome %></td>
        <td><%= hotel.estrelas %></td>
        <td><%= hotel.avaliacao %></td>
        <td><%= hotel.local %></td>
        <td><%= hotel.qtd_camas %></td>
        <td><%= hotel.qnt_banheiros %></td>
        <td><%= hotel.piscina %></td>
        <td><%= hotel.cafe %></td>
        <td><%= hotel.preço %></td>
        <td><%= link_to 'Informações', hotel %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br><font size= "+2"><center>
<% if empresa_signed_in? %>
<%= link_to 'Novo Hotel', new_hotel_path %>
<% end %>
<%= link_to 'Voltar', main_index_url %>
<font/><center/>

<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright © Your Website 2018</p>
  </div>
  <!-- /.container -->
</footer>

hoteis/app/views/hotels/new.html.erb
<center><h1>New Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %><center/>

hoteis/app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<html lang="en"><head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portfolio Item - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-portfolio-item/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-portfolio-item/css/portfolio-item.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="index.html">GORIAN</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <% if cliente_signed_in?  %>

          <%= link_to('Logout', destroy_cliente_session_path, method: :delete) %>

          <%elsif empresa_signed_in?%>

          <%= link_to('Logout', destroy_empresa_session_path, method: :delete) %>

          <%else%>
            <%= link_to "Log in", logins_path  %>
      <% end %>



            </li>
            <li class="nav-item">
              <% if cliente_signed_in?  %>
              <%elsif empresa_signed_in?%>
              <%else%>
              <%= link_to "Cadastros", cadastros_path  %>
                <% end %>

            </li>

          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <!-- Portfolio Item Heading -->
      <h1 class="my-4">Hotel
        <small><%= @hotel.nome %></small>
      </h1>

      <!-- Portfolio Item Row -->
      <div class="row">

        <div class="col-md-8">
          <img src= "<%= @hotel.foto %>"</a>
        </div>

        <div class="col-md-4">
          <h3 class="my-3">Informações Hotel</h3>

          <ul>
          </body></html>

          <p>
            <strong>Nome:</strong>
            <%= @hotel.nome %>
          </p>

          <p>
            <strong>Estrelas:</strong>
            <%= @hotel.estrelas %>
          </p>

          <p>
            <strong>Avaliacao:</strong>
            <%= @hotel.avaliacao %>
          </p>

          <p>
            <strong>Local:</strong>
            <%= @hotel.local %>
          </p>

          <p>
            <strong>Piscina:</strong>
            <%= @hotel.piscina %>
          </p>

          <p>
            <strong>Cafe:</strong>
            <%= @hotel.cafe %>
          </p>

          <p>
            <strong>Preço:</strong>
            <%= @hotel.preço %>
          </p>

          </ul>
        </div>

      </div>
      <!-- /.row -->

      <!-- Related Projects Row -->

      <!-- /.row -->

    </div>
    <!-- /.container -->
    <% if empresa_signed_in? %>
    <%= link_to 'Editar', edit_hotel_path(@hotel) %>
    <%= link_to 'Back', main_index_url %>
    <%= link_to 'Apagar', @hotel, method: :delete, data: { confirm: 'Tem certeza?' } %>

    <% else %>
    <%= link_to 'Back', main_index_url %>
    <% end %>
    <%= link_to 'Apartamentos', apartamentos_path %>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright © Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>