hoteis/config/routes.rb
Rails.application.routes.draw do
  resources :apartamentos
  devise_for :empresas
  devise_for :clientes
  resources :hotels do
    resources :comments
  end
  resources :hotel_empresas
  resources :logins
  resources :cadastros
  mount Commontator::Engine => '/commontator'
  get 'main/index'

  root to: 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hoteis/app/models/apartamento.rb
class Apartamento < ApplicationRecord
    belongs_to :hotel, optional: true
end

hoteis/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hoteis/app/models/cliente.rb
class Cliente < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_commontator
end

hoteis/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :hotel
end

hoteis/app/models/empresa.rb
class Empresa < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

hoteis/app/models/hotel.rb
class Hotel < ApplicationRecord
    acts_as_commontable dependent: :destroy
    has_many :comments
    has_many :apartamentos
end

hoteis/app/controllers/apartamentos_controller.rb
class ApartamentosController < ApplicationController
  before_action :set_apartamento, only: [:show, :edit, :update, :destroy]

  # GET /apartamentos
  # GET /apartamentos.json
  def index
    @apartamentos = Apartamento.all
  end

  # GET /apartamentos/1
  # GET /apartamentos/1.json
  def show
  end

  # GET /apartamentos/new
  def new
    @apartamento = Apartamento.new
  end

  # GET /apartamentos/1/edit
  def edit
  end

  # POST /apartamentos
  # POST /apartamentos.json
  def create
    @apartamento = Apartamento.new(apartamento_params)

    respond_to do |format|
      if @apartamento.save
        format.html { redirect_to @apartamento, notice: 'Apartamento was successfully created.' }
        format.json { render :show, status: :created, location: @apartamento }
      else
        format.html { render :new }
        format.json { render json: @apartamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartamentos/1
  # PATCH/PUT /apartamentos/1.json
  def update
    respond_to do |format|
      if @apartamento.update(apartamento_params)
        format.html { redirect_to @apartamento, notice: 'Apartamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartamento }
      else
        format.html { render :edit }
        format.json { render json: @apartamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartamentos/1
  # DELETE /apartamentos/1.json
  def destroy
    @apartamento.destroy
    respond_to do |format|
      format.html { redirect_to apartamentos_url, notice: 'Apartamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartamento
      @apartamento = Apartamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartamento_params
      params.require(:apartamento).permit(:tamanho, :categoria, :camas, :banheiros)
    end
end

hoteis/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

hoteis/app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
end

hoteis/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @comment = @post.comments.create(params[:comment].permit(:body))
  
    end
  end
  

hoteis/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:foto, :nome, :estrelas, :avaliacao, :local, :qtd_camas, :qnt_banheiros, :piscina, :cafe, :preço)
    end
end

hoteis/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
end

hoteis/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    
    @hotels = Hotel.all

    
  end
end

hoteis/app/controllers/startup_controller.rb
class StartupController < ApplicationController
  def index
  end
end

hoteis/app/helpers/apartamentos_helper.rb
module ApartamentosHelper
end

hoteis/app/helpers/application_helper.rb
module ApplicationHelper
end

hoteis/app/helpers/cadastros_helper.rb
module CadastrosHelper
end

hoteis/app/helpers/hotel_empresa_helper.rb
module HotelEmpresaHelper
end

hoteis/app/helpers/hotels_helper.rb
module HotelsHelper
end

hoteis/app/helpers/login_helper.rb
module LoginHelper
end

hoteis/app/helpers/main_helper.rb
module MainHelper
end

hoteis/app/helpers/startup_helper.rb
module StartupHelper
end

hoteis/app/views/cadastros/index.html.erb
<ul>
    <li>




<br>

<html lang="en"><head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portfolio Item - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-portfolio-item/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-portfolio-item/css/portfolio-item.css" rel="stylesheet">

  </head>


<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="index.html">GORIAN</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if cliente_signed_in?  %>

      <%= link_to('Logout', destroy_cliente_session_path, method: :delete) %>

      <%elsif empresa_signed_in?%>

      <%= link_to('Logout', destroy_empresa_session_path, method: :delete) %>

      <%else%>
        <%= link_to "Log in", logins_path  %>
  <% end %>



        </li>
        <li class="nav-item">
          <% if cliente_signed_in?  %>
          <%elsif empresa_signed_in?%>
          <%else%>
          <%= link_to "Cadastros", cadastros_path  %>
            <% end %>

        </li>

      </ul>
    </div>
  </div>
</nav>
<ul>
    <li>




<br>

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
  <center> <font size= "+10000">  <%= link_to "Cadastrar Cliente", new_cliente_registration_path %>  </font>
    <font size= "+10000"><%= link_to "Cadastrar Empresa", new_empresa_registration_path %></font> </center>

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
    <%= link_to ".", new_cliente_session_path %>

    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright © Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    </li>
</ul>




    </li>
</ul>













<%= link_to "Cadastrar Cliente", new_cliente_registration_path %>
<%= link_to "Cadastrar Empresa", new_empresa_registration_path %>

hoteis/app/views/comments/ _comment.html.erb
<%= stylesheet_link_tag "comment.css" %>

<div>
<div class="baloon z-depth-2"><%= comment.body %></div>
</div>

hoteis/app/views/comments/_form.html.erb
<%= form_for([@hotel, @hotel.comments.build]) do |f| %>


<p>
  <%= f.label :body %><br>
  <%= f.text_field :body %>
</p>
<br>

<p>
  <%= f.submit %>
</p>

<% end %>

hoteis/app/views/logins/index.html.erb
<html lang="en"><head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portfolio Item - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-portfolio-item/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-portfolio-item/css/portfolio-item.css" rel="stylesheet">

  </head>


<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="index.html">GORIAN</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if cliente_signed_in?  %>

      <%= link_to('Logout', destroy_cliente_session_path, method: :delete) %>

      <%elsif empresa_signed_in?%>

      <%= link_to('Logout', destroy_empresa_session_path, method: :delete) %>

      <%else%>
        <%= link_to "Log in", logins_path  %>
  <% end %>



        </li>
        <li class="nav-item">
          <% if cliente_signed_in?  %>
          <%elsif empresa_signed_in?%>
          <%else%>
          <%= link_to "Cadastros", cadastros_path  %>
            <% end %>

        </li>

      </ul>
    </div>
  </div>
</nav>
<ul>
    <li>




<br>

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
  <center> <font size= "+10000">  <%= link_to "Logar Cliente", new_cliente_session_path %>  </font>
    <font size= "+10000"><%= link_to "Logar Empresa", new_empresa_session_path %></font> </center>

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
    <%= link_to ".", new_cliente_session_path %>

    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright © Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    </li>
</ul>

hoteis/app/views/main/index.html.erb
<html lang="en"><head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Gorian - Hotel listing</title>

    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-modern-business/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-modern-business/css/modern-business.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="">Home</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <% if cliente_signed_in?  %>

          <%= link_to('Logout', destroy_cliente_session_path, method: :delete) %>

          <%elsif empresa_signed_in?%>

          <%= link_to('Logout', destroy_empresa_session_path, method: :delete) %>

          <%else%>
            <%= link_to "Log in", logins_path  %>
      <% end %>



            </li>
            <li class="nav-item">
              <% if cliente_signed_in?  %>
              <%elsif empresa_signed_in?%>
              <%else%>
              <%= link_to "Cadastros", cadastros_path  %>
                <% end %>

            </li>

          </ul>
        </div>
      </div>
    </nav>


    <!-- Page Content -->
    <div class="container">

      <h1 class="my-4">Gorian - Hotel listing</h1>




      <!-- Portfolio Section -->
      <h2>Hotéis</h2>
      <div class="row">
      <% @hotels.each do |hotel| %>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img src= "<%= hotel.foto %>" width = "355px" height="200px"</a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#"><td><%= hotel.nome %></td></a>
              </h4>
              <p class="card-text"><td>
                <th>Estrelas</th>
              <th>Local</th>
              <th>Preço</th>
              <br />
              <td><%= hotel.estrelas %></td>
              <td><%= hotel.local %></td>
              <td><%= hotel.preço %></td>
              <td><%= link_to 'Informações', hotel %></td>

            </td></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>

      <!-- /.row -->
      <% if empresa_signed_in? %>
      <center><font size= "+3"><%= link_to 'Novo Hotel', new_hotel_path %><font/><center/>
      <% end %>
      <!-- Features Section -->
      <div class="row">
        <div class="col-lg-6">
          <h2>Equipe de Desenvolvimento</h2>
          <p>Alunos da FGA</p>
          <ul>
            <li>
              <strong>Amor</strong>
            </li>
            <li>Carinho</li>
            <li>Dedicação</li>
            <li>Abençoados com os melhores Monitores</li>
            <li>Renato é o Melhor Professor</li>
          </ul>
          <p>Professor, foi um enorme prazer construir esse projeto!!</p>
        </div>
        <div class="col-lg-6">
          <img class="img-fluid rounded" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Webysther_20160322_-_Logo_UnB_%28sem_texto%29.svg/1280px-Webysther_20160322_-_Logo_UnB_%28sem_texto%29.svg.png700x450" alt="">
        </div>
      </div>
      <!-- /.row -->

      <hr>


    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright © Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

hoteis/app/views/startup/index.html.erb
<h1>Startup#index</h1>
<p>Find me in app/views/startup/index.html.erb</p>